<?php

namespace Mparaiso;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-21 at 14:52:23.
 */
class SimpleRssTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SimpleRss
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SimpleRss(array());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SimpleRss::getChannel
     * @todo   Implement testGetChannel().
     */
    public function testGetChannel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SimpleRss::setChannel
     * @todo   Implement testSetChannel().
     */
    public function testSetChannel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SimpleRss::getBuilder
     * @todo   Implement testGetBuilder().
     */
    public function testGetBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SimpleRss::setBuilder
     * @todo   Implement testSetBuilder().
     */
    public function testSetBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SimpleRss::generate
     * @todo   Implement testGenerate().
     */
    public function testGenerate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
